### ISSUE TITLE
Don't use prepublish to actually do prepublish related tasks

### ISSUE THREAD

**Issue by dominykas** [bmeck/node-cookiejar#22]
See https://github.com/npm/npm/issues/3059 - `prepublish` also runs during `npm install` inside package's folder, so essentially every time someone clones from git, and runs `npm install` so they can dev, they get an error, like so:

```
> cookiejar@2.0.3 prepublish /Users/dominykas/devel/experiments/tmp/node-cookiejar
> jshint cookiejar.js && git tag $npm_package_version && git push origin master && git push origin --tags

fatal: tag '2.0.3' already exists
```

You can use in-publish to circumvent this: https://www.npmjs.com/package/in-publish

**Comment by andyburke** [comment]
This was addressed in 79a66df0ded433f38eb5aa3fe334a4d9cf9174fc
