### ISSUE TITLE
Provide facility for retrieving all cookies; a wildcard CookieAccessInfo

### ISSUE THREAD

**Issue by keithamus** [bmeck/node-cookiejar#24]
Hey @bmeck, thanks for the awesome project! We use it inside of the [chai-http plugin](https://github.com/chaijs/chai-http) and it works great!

One thing that would be really useful for our users - given that chai-http is a test framework - is to get cookies irrespective of access settings (See [this issue](https://github.com/chaijs/chai-http/issues/43) for more). Perhaps having a sentinel of `Cookie.CookieAccessInfo.All` could be used to flag to `cookie.match()` to automatically return true?

Any thoughts on this would be much appreciated. If you like the idea I'm happy to PR it :smile:

**Comment by bmeck** [comment]
this seems pretty sane to me. just make a PR with a test.
