### ISSUE TITLE
bug: TypeError: access_info.domain.replace is not a function

### ISSUE THREAD

**Issue by gebrits** [bmeck/node-cookiejar#26]
Found a bug that only happens sporadically: `TypeError: access_info.domain.replace is not a function`

See attached screenshot
<img width="771" alt="screen shot 2016-11-16 at 21 49 34" src="https://cloud.githubusercontent.com/assets/393259/20365333/de2ec930-ac46-11e6-86b2-45fc3c445c84.png">

For some reason `access_info.domain` is a cookieAccessInfo instead of a plain string, causing the problem.

**Comment by andyburke** [comment]
Any chance you have a bit more of a callstack? I'm only a sporadic contributor, but I don't see us creating any CookieAccessInfo objects internally, I'd be curious to see if there's one being created in the deeper callstack.
