### ISSUE TITLE
No key value pair found breaks parsing

### ISSUE THREAD

**Issue by bfelbo** [bmeck/node-cookiejar#33]
Hi,

I'm using cookiejar as part of the popular scraping package [x-ray](https://github.com/matthewmueller/x-ray). For some links, cookiejar will break with an error `TypeError: Cannot read property '1' of null` with the stack trace referring to https://github.com/bmeck/node-cookiejar/blob/master/cookiejar.js#L72. It breaks even when used within a try/except block so I can't do much to prevent this problem in my code. Can you give me some advice on how to fix this issue or help me make cookiejar throw a relevant error that I can catch downstream?

There's a reproducible example here:
https://github.com/matthewmueller/x-ray/issues/234

**Comment by danielmcq** [comment]
I've ran into this error myself. I was able to avoid it by ensuring that the cookies I was putting into cookiejar didn't have any empty strings or incomplete values. However, I think we can probably get some tweaks made to the code to avoid this situation.

**Comment by danielmcq** [comment]
I have a PR which fixes this issue. I tested it against the example given on matthewmueller/x-ray#234.

**Comment by bfelbo** [comment]
Great, thanks a lot!
