### ISSUE TITLE
Value of cookie is not decoded

### ISSUE THREAD

**Issue by fluggo** [bmeck/node-cookiejar#37]
If the cookie's value contains an equal sign, it will be URL-encoded:

```
sample=e30%3D; Path=/
```

This library should decode the value as part of parsing.

**Comment by bmeck** [comment]
Per https://datatracker.ietf.org/doc/html/rfc6265 and the subsequent https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis-07 , no processing is done when reading value strings:

> The semantics of the cookie-value are not defined by this document.

>   To maximize compatibility with user agents, servers that wish to
>   store arbitrary data in a cookie-value SHOULD encode that data, for
>   example, using Base64 [RFC4648].

**Comment by fluggo** [comment]
Fair point, I see that for cookie-value in the BN, they do allow equal signs. What a weird header.

**Comment by bmeck** [comment]
I wouldn't disagree with that statement.
