### ISSUE TITLE
Invalid cookie header encountered. Header: ' httponly'

### ISSUE THREAD

**Issue by makoru-hikage** [bmeck/node-cookiejar#41]
This happens when I parse a cookie string that has an 'HttpOnly' attribute. I usually use it along with `Secure` attribute.

Here are the specifications for the HttpOnly attribute: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies

JS libraries like [cookie](https://www.npmjs.com/package/cookie) has the option to set `HttpOnly` to some cookies. We need to patch it. Thank you.

**Comment by bmeck** [comment]
Do you have an example string for parsing, there is support already for HttpOnly. Perhaps the `set-cookie` header is oddly formatted? Given the example on the page linked it seems to work fine:

```console
> new Cookie('id=a3fWa; Expires=Thu, 21 Oct 2021 07:28:00 GMT; Secure; HttpOnly')
Cookie {
  name: 'id',
  value: 'a3fWa',
  expiration_date: 1634801280000,
  path: '/',
  explicit_path: false,
  domain: undefined,
  explicit_domain: false,
  secure: true,
  noscript: true
}
```

**Comment by makoru-hikage** [comment]
I'm sorry; I forgot I how I was able to trigger the `console.warn` that told me the message:

`Invalid cookie header encountered. Header: ' httponly'`

Notice the space in `' httponly'`. I am certain that the `set-cookie` header that time was oddly formatted, yet I forgot how I made it.

No need to patch anything. Thank you @bmeck for the timely response.
